In [15]:
import numpy as np
with open('input.txt') as file:
    lines = file.read().split('\n')
print(lines)
data = np.zeros((len(lines[0]), len(lines)),dtype=int)

for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        data[i, j] = lines[i][j]
print(data)
print('')

flash_counter = 0

def get_range(index):
    lower = index - 1
    upper = index + 2
    if index == 0:
        lower = index
    elif index >= data.shape[0]-1:
        upper =  index + 1
    return(range(lower, upper))

def flash(i, j):
    global flash_counter
    flash_counter += 1
    data[i, j] = 0
    for ii in get_range(i):
        for jj in get_range(j):
            if data[ii, jj] > 0:
                data[ii, jj] += 1
            if data[ii, jj] > 9:
                flash(ii, jj)
                

# for iteration in range(100):
iteration = 0
all_is_zero = False
while all_is_zero == False:
    iteration += 1

    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            data[i, j] += 1
    
    # print('')
    # print('----')
    # print(data)
    # print('')

    
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            if data[i, j] > 9:
                flash(i, j)
                
    # print(data)
    # print('----')

    all_is_zero = not np.any(data)
    
print(f'all zero iteration: {iteration}')
print(f'flash count: {flash_counter}')




['4472562264', '8631517827', '7232144146', '2447163824', '1235272671', '5133527146', '6511372417', '3841841614', '8621368782', '3246336677']
[[4 4 7 2 5 6 2 2 6 4]
 [8 6 3 1 5 1 7 8 2 7]
 [7 2 3 2 1 4 4 1 4 6]
 [2 4 4 7 1 6 3 8 2 4]
 [1 2 3 5 2 7 2 6 7 1]
 [5 1 3 3 5 2 7 1 4 6]
 [6 5 1 1 3 7 2 4 1 7]
 [3 8 4 1 8 4 1 6 1 4]
 [8 6 2 1 3 6 8 7 8 2]
 [3 2 4 6 3 3 6 6 7 7]]

all zero iteration: 212
flash count: 3440
