In [44]:
import numpy as np
global data
def check_position(i, j):
    global data
    global size
    value = data[i, j]
    data[i, j] = 0
    if i > 0:
        testval = data[i-1, j]
        if testval > value and testval < 9:
            size += 1
            basin_contents.append(testval)
            check_position(i-1, j)
            data[i-1, j] = 0
    if i < data.shape[0] - 1:
        testval = data[i+1, j]
        if testval > value and testval < 9:
            size += 1
            basin_contents.append(testval)
            check_position(i+1, j)
            data[i+1, j] = 0
    if j > 0:
        testval = data[i, j-1]
        if testval > value and testval < 9:
            size += 1
            basin_contents.append(testval)
            check_position(i, j-1)
            data[i, j-1] = 0
    if j < data.shape[1] - 1:
        testval = data[i, j+1]
        if testval > value and testval < 9:
            size += 1
            basin_contents.append(testval)
            check_position(i, j+1)
            data[i, j+1] = 0

with open('input.txt') as file:
    input_list = [[int(x) for x in line] for line in file.read().split('\n')]
data = np.array(input_list, dtype=int)
print(data)
# print(data.shape)
total_risk = 0
basin_sizes = []
basins = []
print(f'shape: {data.shape}')
for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        value = data[i, j]
        too_tall = False
        if i > 0:
            if value >= data[i-1, j]:
                too_tall = True
        if i < data.shape[0] - 1:
            if value >= data[i+1, j]:
                too_tall = True
        if j > 0:
            if value >= data[i, j-1]:
                too_tall = True
        if j < data.shape[1] - 1:
            if value >= data[i, j+1]:
                too_tall = True
        if not too_tall:
            # This is a basin
            # Calculate the size of the basin by expanding incrementally
            finished = False
            size = 1
            basin_contents = [value]
            check_position(i, j)
            basin_sizes.append(size)
            basins.append(basin_contents)

print(f'basin_sizes: {basin_sizes}')
for basin in basins:
    print(basin)

print(data)

basin_sizes.sort(reverse=True)
print(basin_sizes)
print(basin_sizes[0] * basin_sizes[1] * basin_sizes[2])


[[8 7 5 ... 5 6 7]
 [9 8 6 ... 4 5 6]
 [1 9 7 ... 3 4 5]
 ...
 [7 6 4 ... 9 7 8]
 [9 6 5 ... 9 8 9]
 [8 7 6 ... 9 9 9]]
shape: (100, 100)
basin_sizes: [9, 41, 20, 29, 6, 24, 61, 11, 2, 57, 48, 17, 35, 2, 59, 2, 78, 88, 43, 36, 42, 33, 23, 5, 75, 36, 53, 45, 18, 19, 8, 8, 12, 31, 49, 6, 24, 7, 8, 18, 37, 24, 4, 36, 13, 75, 44, 13, 15, 73, 2, 20, 2, 49, 16, 30, 65, 6, 5, 37, 29, 5, 32, 66, 58, 26, 3, 91, 69, 24, 5, 21, 43, 20, 2, 8, 60, 2, 8, 6, 38, 23, 3, 44, 11, 32, 2, 12, 30, 41, 5, 34, 27, 88, 36, 61, 17, 41, 26, 3, 18, 11, 6, 2, 57, 3, 92, 14, 45, 2, 88, 16, 27, 37, 3, 32, 36, 9, 22, 48, 12, 36, 70, 61, 10, 93, 31, 49, 22, 5, 24, 17, 3, 6, 12, 22, 26, 7, 10, 23, 4, 27, 45, 18, 3, 78, 71, 100, 26, 18, 99, 5, 5, 35, 87, 20, 57, 3, 25, 27, 6, 62, 17, 16, 73, 80, 4, 2, 39, 55, 64, 56, 2, 4, 15, 13, 10, 47, 4, 33, 5, 23, 98, 11, 3, 103, 54, 82, 85, 9, 41, 19, 58, 16, 31, 16, 44, 9, 88, 22, 31, 6, 5, 30, 3, 24, 11, 4, 34, 50, 69, 8, 57, 11, 76, 3, 39, 4, 54, 4, 21, 6, 8, 19, 82, 7, 60, 27